### ISSUE TITLE
Many commands don't work (Flank/Cover/Suppressive fire)

### ISSUE THREAD

**Issue by Shodan0000** [Asaayu/integrated-voice-control-system#5]
First off. Thank you for making this. Having this integrated in Arma works a lot better than articulate, which would often get stuck in the orders menu.

Unfortunately many commands don't work as needed. These include the following:

-Flanking / cover / suppressive fire.

All these commands result in move orders and not in the behavior that is expected. The suppression worked once, but after I chose it it would also turn in a move order and everyone was saying "Negative". When I chose the order in the context menu by hand they did do suppressive fire.

Flanking and Covering will just move soldiers around and won't execute the actual commands.

**Comment by Asaayu** [comment]
> The suppression worked once, but after I chose it it would also turn in a move order and everyone was saying "Negative". When I chose the order in the context menu by hand they did do suppressive fire.

Unsure what would be causing this issue, it may have been fixed in the 2.0 rework, let me know if you still encounter the issue.

> Flanking and Covering will just move soldiers around and won't execute the actual commands.

Unfortunately, there are no commands avaliable to replicate the behavour of flanking and cover exactly, so what they do at the moment is the best avaliable representation of the original commands.
